//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace win81FactoryTest.AppResources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("win81FactoryTest.AppResources.Res", typeof(Res).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Accelerometer.
        /// </summary>
        internal static string Accelerometer {
            get {
                return ResourceManager.GetString("Accelerometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Accuracy.
        /// </summary>
        internal static string Accuracy {
            get {
                return ResourceManager.GetString("Accuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Execute Action#1.
        /// </summary>
        internal static string Action1 {
            get {
                return ResourceManager.GetString("Action1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Execute Action#2.
        /// </summary>
        internal static string Action2 {
            get {
                return ResourceManager.GetString("Action2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Execute Action#3.
        /// </summary>
        internal static string Action3 {
            get {
                return ResourceManager.GetString("Action3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Light Reading.
        /// </summary>
        internal static string ALSReading {
            get {
                return ResourceManager.GetString("ALSReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Audio file not found.
        /// </summary>
        internal static string AudioFileNotFound {
            get {
                return ResourceManager.GetString("AudioFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please proceed with the tests.
        /// </summary>
        internal static string AudioHeadsetContinue {
            get {
                return ResourceManager.GetString("AudioHeadsetContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please plug in [Headset], then click [Play]  Button to start playing audio. Click [Next] when audio finishes.
        /// </summary>
        internal static string AudioHeadsetPlay {
            get {
                return ResourceManager.GetString("AudioHeadsetPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please plug in [Headset], then click [Record] Button to start recording..
        /// </summary>
        internal static string AudioHeadsetRecord {
            get {
                return ResourceManager.GetString("AudioHeadsetRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Next.
        /// </summary>
        internal static string AudioNext {
            get {
                return ResourceManager.GetString("AudioNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Play.
        /// </summary>
        internal static string AudioPlay {
            get {
                return ResourceManager.GetString("AudioPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Play Audio file.
        /// </summary>
        internal static string AudioPlayAudio {
            get {
                return ResourceManager.GetString("AudioPlayAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a PlayLeftChannel.
        /// </summary>
        internal static string AudioPlayL {
            get {
                return ResourceManager.GetString("AudioPlayL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a PlayRightChannel.
        /// </summary>
        internal static string AudioPlayR {
            get {
                return ResourceManager.GetString("AudioPlayR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Recording.
        /// </summary>
        internal static string AudioRecording {
            get {
                return ResourceManager.GetString("AudioRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Recording now....
        /// </summary>
        internal static string AudioRecordingNow {
            get {
                return ResourceManager.GetString("AudioRecordingNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please remove [Headset], then click [Play]  Button to start playing audio. Click [Next] when audio finishes.
        /// </summary>
        internal static string AudioSpeakerPlay {
            get {
                return ResourceManager.GetString("AudioSpeakerPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please remove [Headset], then click [Record] Button to start recording..
        /// </summary>
        internal static string AudioSpeakerRecord {
            get {
                return ResourceManager.GetString("AudioSpeakerRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Start.
        /// </summary>
        internal static string AudioStart {
            get {
                return ResourceManager.GetString("AudioStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Stop.
        /// </summary>
        internal static string AudioStop {
            get {
                return ResourceManager.GetString("AudioStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Battery.
        /// </summary>
        internal static string Battery {
            get {
                return ResourceManager.GetString("Battery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Battery % :.
        /// </summary>
        internal static string Battery_bat {
            get {
                return ResourceManager.GetString("Battery_bat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Charging Rate :.
        /// </summary>
        internal static string Battery_chargeRate {
            get {
                return ResourceManager.GetString("Battery_chargeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Charge Status :.
        /// </summary>
        internal static string Battery_chargeStatus {
            get {
                return ResourceManager.GetString("Battery_chargeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Power Status :.
        /// </summary>
        internal static string Battery_pwrStatus {
            get {
                return ResourceManager.GetString("Battery_pwrStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Charging.
        /// </summary>
        internal static string BatteryCharging {
            get {
                return ResourceManager.GetString("BatteryCharging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Discharging.
        /// </summary>
        internal static string BatteryDischarging {
            get {
                return ResourceManager.GetString("BatteryDischarging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please let device charge for at least 1 minutes.
        /// </summary>
        internal static string BatteryNote {
            get {
                return ResourceManager.GetString("BatteryNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Offline.
        /// </summary>
        internal static string BatteryOffline {
            get {
                return ResourceManager.GetString("BatteryOffline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Online.
        /// </summary>
        internal static string BatteryOnline {
            get {
                return ResourceManager.GetString("BatteryOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Action#.
        /// </summary>
        internal static string BioAct {
            get {
                return ResourceManager.GetString("BioAct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Enrollment Fail.
        /// </summary>
        internal static string BioEnrollFail {
            get {
                return ResourceManager.GetString("BioEnrollFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Enrollment Succeed.
        /// </summary>
        internal static string BioEnrollSuccess {
            get {
                return ResourceManager.GetString("BioEnrollSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Move your finger more slowly on the fingerprint reader..
        /// </summary>
        internal static string BioFast {
            get {
                return ResourceManager.GetString("BioFast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Position your finger lower on the fingerprint reader..
        /// </summary>
        internal static string BioHigh {
            get {
                return ResourceManager.GetString("BioHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Position your finger more to the right on the fingerprint reader..
        /// </summary>
        internal static string BioLeft {
            get {
                return ResourceManager.GetString("BioLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Position your finger higher on the fingerprint reader..
        /// </summary>
        internal static string BioLow {
            get {
                return ResourceManager.GetString("BioLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The fingerprint reader could not capture a good sample. Check to be sure the sensor is clean..
        /// </summary>
        internal static string BioMergeFail {
            get {
                return ResourceManager.GetString("BioMergeFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Biometric.
        /// </summary>
        internal static string Biometric {
            get {
                return ResourceManager.GetString("Biometric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Another sample is needed for the current enrollment template..
        /// </summary>
        internal static string BioMoredata {
            get {
                return ResourceManager.GetString("BioMoredata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The fingerprint reader could not capture a good sample. Check to be sure the sensor is clean..
        /// </summary>
        internal static string BioPoorQuality {
            get {
                return ResourceManager.GetString("BioPoorQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Position your finger more to the left on the fingerprint reader..
        /// </summary>
        internal static string BioRight {
            get {
                return ResourceManager.GetString("BioRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Use a longer stroke when scanning your fingerprint..
        /// </summary>
        internal static string BioShort {
            get {
                return ResourceManager.GetString("BioShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Hold your finger flat and straight when you use the fingerprint reader..
        /// </summary>
        internal static string BioSkew {
            get {
                return ResourceManager.GetString("BioSkew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Move your finger more quickly on the fingerprint reader..
        /// </summary>
        internal static string BioSlow {
            get {
                return ResourceManager.GetString("BioSlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Swipe your finger on the sensor....
        /// </summary>
        internal static string BioSwipe {
            get {
                return ResourceManager.GetString("BioSwipe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Swpie Status :.
        /// </summary>
        internal static string BioswpStatus {
            get {
                return ResourceManager.GetString("BioswpStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Bluetooth.
        /// </summary>
        internal static string Bluetooth {
            get {
                return ResourceManager.GetString("Bluetooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Brightness.
        /// </summary>
        internal static string Brightness {
            get {
                return ResourceManager.GetString("Brightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Start to test brightness.....
        /// </summary>
        internal static string Brightness_text {
            get {
                return ResourceManager.GetString("Brightness_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a End Brightness test.
        /// </summary>
        internal static string Brightness_text2 {
            get {
                return ResourceManager.GetString("Brightness_text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Buttons.
        /// </summary>
        internal static string Buttons {
            get {
                return ResourceManager.GetString("Buttons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Capture.
        /// </summary>
        internal static string Capture {
            get {
                return ResourceManager.GetString("Capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Clear.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Compass.
        /// </summary>
        internal static string Compass {
            get {
                return ResourceManager.GetString("Compass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Magnetic.
        /// </summary>
        internal static string CompassMagnetic {
            get {
                return ResourceManager.GetString("CompassMagnetic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Display.
        /// </summary>
        internal static string Display {
            get {
                return ResourceManager.GetString("Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a External Display.
        /// </summary>
        internal static string ExtDisplay {
            get {
                return ResourceManager.GetString("ExtDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cannot load media file.
        /// </summary>
        internal static string ExtDisplay_Err {
            get {
                return ResourceManager.GetString("ExtDisplay_Err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please connect your external display.
        /// </summary>
        internal static string ExtDisplay_notfound {
            get {
                return ResourceManager.GetString("ExtDisplay_notfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DisplayPort One.
        /// </summary>
        internal static string ExtDisplayOne {
            get {
                return ResourceManager.GetString("ExtDisplayOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DisplayPort Two.
        /// </summary>
        internal static string ExtDisplayTwo {
            get {
                return ResourceManager.GetString("ExtDisplayTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fail.
        /// </summary>
        internal static string Fail {
            get {
                return ResourceManager.GetString("Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fan.
        /// </summary>
        internal static string Fan {
            get {
                return ResourceManager.GetString("Fan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Front Photo.
        /// </summary>
        internal static string FrontCamera {
            get {
                return ResourceManager.GetString("FrontCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cannot find camera!! Please make sure &lt;FrontCamera&gt; is set up correctly in SFTConfig.xml [Refer to the Camera Info in Settings icon].
        /// </summary>
        internal static string FrontCameraHint {
            get {
                return ResourceManager.GetString("FrontCameraHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Front Record.
        /// </summary>
        internal static string FrontCameraRec {
            get {
                return ResourceManager.GetString("FrontCameraRec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cannot find camera!! Please make sure &lt;FrontCameraRec&gt; is set up correctly in SFTConfig.xml [Refer to the Camera Info in Settings icon].
        /// </summary>
        internal static string FrontCameraRecHint {
            get {
                return ResourceManager.GetString("FrontCameraRecHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Accuracy.
        /// </summary>
        internal static string GeolocationAccuracy {
            get {
                return ResourceManager.GetString("GeolocationAccuracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Latitude.
        /// </summary>
        internal static string GeolocationLatitude {
            get {
                return ResourceManager.GetString("GeolocationLatitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Longitude.
        /// </summary>
        internal static string GeolocationLongitude {
            get {
                return ResourceManager.GetString("GeolocationLongitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Position source.
        /// </summary>
        internal static string GeolocationPositionSource {
            get {
                return ResourceManager.GetString("GeolocationPositionSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a GPS.
        /// </summary>
        internal static string GPS {
            get {
                return ResourceManager.GetString("GPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Gyrometer.
        /// </summary>
        internal static string Gyrometer {
            get {
                return ResourceManager.GetString("Gyrometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Volume Down.
        /// </summary>
        internal static string HardwareBtnVolumeDown {
            get {
                return ResourceManager.GetString("HardwareBtnVolumeDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Volume Up.
        /// </summary>
        internal static string HardwareBtnVolumeUp {
            get {
                return ResourceManager.GetString("HardwareBtnVolumeUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Windows Button.
        /// </summary>
        internal static string HardwareBtnWinBtn {
            get {
                return ResourceManager.GetString("HardwareBtnWinBtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a HDMI Display.
        /// </summary>
        internal static string HDMIDisplay {
            get {
                return ResourceManager.GetString("HDMIDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Headset and Mic.
        /// </summary>
        internal static string Headset {
            get {
                return ResourceManager.GetString("Headset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Hibernate.
        /// </summary>
        internal static string Hibernate {
            get {
                return ResourceManager.GetString("Hibernate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please hide the sensor.
        /// </summary>
        internal static string HideSensor {
            get {
                return ResourceManager.GetString("HideSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Inclinometer.
        /// </summary>
        internal static string Inclinometer {
            get {
                return ResourceManager.GetString("Inclinometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a IR Camera.
        /// </summary>
        internal static string IRCamera {
            get {
                return ResourceManager.GetString("IRCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Keyboard.
        /// </summary>
        internal static string Keyboard {
            get {
                return ResourceManager.GetString("Keyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Shortcut buttons.
        /// </summary>
        internal static string KeyboardHook {
            get {
                return ResourceManager.GetString("KeyboardHook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Keyboard.
        /// </summary>
        internal static string KeyboardNew {
            get {
                return ResourceManager.GetString("KeyboardNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Hardware Button.
        /// </summary>
        internal static string Keypad {
            get {
                return ResourceManager.GetString("Keypad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a LAN Port.
        /// </summary>
        internal static string LAN {
            get {
                return ResourceManager.GetString("LAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Led.
        /// </summary>
        internal static string Led {
            get {
                return ResourceManager.GetString("Led", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Please press the number key according to the LED.
        /// </summary>
        internal static string LedMessage {
            get {
                return ResourceManager.GetString("LedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Light.
        /// </summary>
        internal static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Magnetic heading.
        /// </summary>
        internal static string MagneticHeading {
            get {
                return ResourceManager.GetString("MagneticHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Device Not Found.
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Numberpad.
        /// </summary>
        internal static string Numberpad {
            get {
                return ResourceManager.GetString("Numberpad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Orientation.
        /// </summary>
        internal static string Orientation {
            get {
                return ResourceManager.GetString("Orientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pass.
        /// </summary>
        internal static string Pass {
            get {
                return ResourceManager.GetString("Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pause.
        /// </summary>
        internal static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pen.
        /// </summary>
        internal static string Pen {
            get {
                return ResourceManager.GetString("Pen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Eraser to clear Yellow.
        /// </summary>
        internal static string PenInstruction1 {
            get {
                return ResourceManager.GetString("PenInstruction1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Clear red dots.
        /// </summary>
        internal static string PenInstruction2 {
            get {
                return ResourceManager.GetString("PenInstruction2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Rear Photo.
        /// </summary>
        internal static string RearCamera {
            get {
                return ResourceManager.GetString("RearCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cannot find camera!! Please make sure &lt;RearCamera&gt; is set up correctly in SFTConfig.xml [Refer to the Camera Info in Settings icon].
        /// </summary>
        internal static string RearCameraHint {
            get {
                return ResourceManager.GetString("RearCameraHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Rear Record.
        /// </summary>
        internal static string RearCameraRec {
            get {
                return ResourceManager.GetString("RearCameraRec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cannot find camera!! Please make sure &lt;RearCameraRec&gt; is set up correctly in SFTConfig.xml [Refer to the Camera Info in Settings icon].
        /// </summary>
        internal static string RearCameraRecHint {
            get {
                return ResourceManager.GetString("RearCameraRecHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Config Drives.
        /// </summary>
        internal static string RemovableArgsDrive {
            get {
                return ResourceManager.GetString("RemovableArgsDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Available space to current user.
        /// </summary>
        internal static string RemovableAvailableFreeSpace {
            get {
                return ResourceManager.GetString("RemovableAvailableFreeSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Removable Device.
        /// </summary>
        internal static string RemovableDevice {
            get {
                return ResourceManager.GetString("RemovableDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Drive type.
        /// </summary>
        internal static string RemovableDriveType {
            get {
                return ResourceManager.GetString("RemovableDriveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Total available space.
        /// </summary>
        internal static string RemovableTotalFreeSpace {
            get {
                return ResourceManager.GetString("RemovableTotalFreeSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Total size.
        /// </summary>
        internal static string RemovableTotalSize {
            get {
                return ResourceManager.GetString("RemovableTotalSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resume.
        /// </summary>
        internal static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Retry.
        /// </summary>
        internal static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Run All.
        /// </summary>
        internal static string RunAll {
            get {
                return ResourceManager.GetString("RunAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Serial Port.
        /// </summary>
        internal static string SerialPort {
            get {
                return ResourceManager.GetString("SerialPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Fail Result:.
        /// </summary>
        internal static string SerialPort_Fail {
            get {
                return ResourceManager.GetString("SerialPort_Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pass Result:.
        /// </summary>
        internal static string SerialPort_Pass {
            get {
                return ResourceManager.GetString("SerialPort_Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SIM Card.
        /// </summary>
        internal static string SIM {
            get {
                return ResourceManager.GetString("SIM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SIM inserted.
        /// </summary>
        internal static string SIMFound {
            get {
                return ResourceManager.GetString("SIMFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SIM card not found.
        /// </summary>
        internal static string SIMNotFound {
            get {
                return ResourceManager.GetString("SIMNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sleep.
        /// </summary>
        internal static string Sleep {
            get {
                return ResourceManager.GetString("Sleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Speaker and mic.
        /// </summary>
        internal static string Speaker {
            get {
                return ResourceManager.GetString("Speaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Speaker.
        /// </summary>
        internal static string SpeakerOnly {
            get {
                return ResourceManager.GetString("SpeakerOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Info.
        /// </summary>
        internal static string SysInfo {
            get {
                return ResourceManager.GetString("SysInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a System Info.
        /// </summary>
        internal static string SystemInfo {
            get {
                return ResourceManager.GetString("SystemInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a  Test.
        /// </summary>
        internal static string Test {
            get {
                return ResourceManager.GetString("Test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Touch.
        /// </summary>
        internal static string Touch {
            get {
                return ResourceManager.GetString("Touch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Touchpad.
        /// </summary>
        internal static string Touchpad {
            get {
                return ResourceManager.GetString("Touchpad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Double Click.
        /// </summary>
        internal static string TouchpadDouble {
            get {
                return ResourceManager.GetString("TouchpadDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Left Click.
        /// </summary>
        internal static string TouchpadLeft {
            get {
                return ResourceManager.GetString("TouchpadLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Right Click.
        /// </summary>
        internal static string TouchpadRight {
            get {
                return ResourceManager.GetString("TouchpadRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Clear all grid.
        /// </summary>
        internal static string TouchTest1 {
            get {
                return ResourceManager.GetString("TouchTest1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a -touch point test: .
        /// </summary>
        internal static string TouchTest2 {
            get {
                return ResourceManager.GetString("TouchTest2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Swipe from left to right with {0} fingers.
        /// </summary>
        internal static string TouchTest3 {
            get {
                return ResourceManager.GetString("TouchTest3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a True heading.
        /// </summary>
        internal static string TrueHeading {
            get {
                return ResourceManager.GetString("TrueHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a File Upload.
        /// </summary>
        internal static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Volume Down.
        /// </summary>
        internal static string VolumeDown {
            get {
                return ResourceManager.GetString("VolumeDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Volume Up.
        /// </summary>
        internal static string VolumeUp {
            get {
                return ResourceManager.GetString("VolumeUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Wait... .
        /// </summary>
        internal static string Wait {
            get {
                return ResourceManager.GetString("Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a WAxis.
        /// </summary>
        internal static string WAxis {
            get {
                return ResourceManager.GetString("WAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Wifi.
        /// </summary>
        internal static string WiFi {
            get {
                return ResourceManager.GetString("WiFi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a X Axis.
        /// </summary>
        internal static string XAxis {
            get {
                return ResourceManager.GetString("XAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a X Degree.
        /// </summary>
        internal static string XDegree {
            get {
                return ResourceManager.GetString("XDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Y Axis.
        /// </summary>
        internal static string YAxis {
            get {
                return ResourceManager.GetString("YAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Y Degree.
        /// </summary>
        internal static string YDegree {
            get {
                return ResourceManager.GetString("YDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Z Axit.
        /// </summary>
        internal static string ZAxis {
            get {
                return ResourceManager.GetString("ZAxis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Z Degree.
        /// </summary>
        internal static string ZDegree {
            get {
                return ResourceManager.GetString("ZDegree", resourceCulture);
            }
        }
    }
}
